version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  deploy_app:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          command: |
            aws eks update-kubeconfig --name $CLUSTER_NAME
          name: Update kubeconfig
      - run:
          command: |
            docker --version
          name: Docker version

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_app
