version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  deploy_app:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      
      - run:
          command:
            aws eks update-kubeconfig --name $CLUSTER_NAME
          name: Update kubeconfig

      - run:
          command:
            docker login index.docker.io/faiiinttt/simple-website -u $DOCKER_USER -p $DOCKER_PASSWORD
          name: Docker login

      - run:
          command: |
            curl -L "https://tuf.werf.io/targets/releases/1.2.21/linux-amd64/bin/werf" -o /tmp/werf
            sudo install /tmp/werf /usr/local/bin/werf
          name: Install Werf

      - run:
          command:
            werf converge --repo index.docker.io/faiiinttt/simple-website
          name: Deploy application using Werf
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_app
